baseURL = 'https://think.h-group.net/'
languageCode = 'en-us'
title = '<think/>'
theme = 'hugo-bearcub'
copyright = "Dennis Hammer"
enableRobotsTXT = true
[permalinks]
  blog = "/blog/:slug/"
  tags = "/tags/:slug"
[params]
  description = "Dennis Hammer's blog with observations about tech, travel, wine, food and other things"
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "think"
  themeStyle = "herman"
  generateSocialCard = true
  [params.author]
    name = "Dennis Hammer"
    email = "think@h-group.net"
